version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hentak-kaki"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pydelgwo9fde"
s3_prefix = "hentak-kaki"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "TelegramBotToken=\"\" RedditClientId=\"\" RedditClientSecret=\"\" RedditUsername=\"\" RedditPassword=\"\""
