AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: hentak-kaki

Parameters:
  TelegramBotToken:
    Description: Bot token
    Type: String
  RedditClientId:
    Type: String
  RedditClientSecret:
    Type: String
  RedditUsername:
    Type: String
  RedditPassword:
    Type: String

Globals:
  Function:
    MemorySize: 256
    Timeout: 30

Resources:
  BotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      FunctionName: hentak-kaki
      Handler: lambda.lambdaHandler
      Runtime: nodejs16.x
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          NODE_ENV: production
          NODE_OPTIONS: --enable-source-maps
          REDDIT_CLIENT_ID: !Ref RedditClientId
          REDDIT_CLIENT_SECRET: !Ref RedditClientSecret
          REDDIT_USERNAME: !Ref RedditUsername
          REDDIT_PASSWORD: !Ref RedditPassword
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SectorTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriberTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CacheTable
  TimerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      FunctionName: hentak-kaki-timer
      Handler: lambda.timer
      Runtime: nodejs16.x
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          NODE_ENV: production
          NODE_OPTIONS: --enable-source-maps
          REDDIT_CLIENT_ID: !Ref RedditClientId
          REDDIT_CLIENT_SECRET: !Ref RedditClientSecret
          REDDIT_USERNAME: !Ref RedditUsername
          REDDIT_PASSWORD: !Ref RedditPassword
      Events:
        ScheduledRun:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Name: hentak-kaki-timer-schedule
            Description: Runs once an hour
            Enabled: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SectorTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriberTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CacheTable
  SessionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: chatId
        Type: Number
      TableName: hentak-kaki-session-table
  SectorTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Name
        Type: String
      TableName: hentak-kaki-sector-table
  SubscriberTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: chatId
        Type: Number
      TableName: hentak-kaki-subscriber-table
  CacheTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: hentak-kaki-cache-table

Outputs:
  FunctionUrlEndpoint:
    Description: "Lambda Function URL Endpoint"
    Value:
      Fn::GetAtt: BotFunctionUrl.FunctionUrl

